version: '3'
services:
  db-server:
    image: mysql:latest
    environment:
    - MYSQL_DATABASE=polemarch
    - MYSQL_ROOT_PASSWORD=polemarch
    - MYSQL_USER=polemarch
    - MYSQL_PASSWORD=polemarch
    - MYSQL_HOST=%
    volumes:
      - "db_data:/var/lib/mysql"
  memcache-server:
    image: memcached
  rabbitmq-server:
    image: rabbitmq:latest
    environment:
    - RABBITMQ_DEFAULT_USER=polemarch
    - RABBITMQ_DEFAULT_PASS=polemarch
    - RABBITMQ_DEFAULT_VHOST=polemarch
  polemarch:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    command: |
      /bin/bash -c "
        set -e
        curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh | tee ./wait-for-it.sh
        chmod +x wait-for-it.sh
        ./wait-for-it.sh db-server:3306 -s -t 30
        ./wait-for-it.sh rabbitmq-server:5672 -s -t 30
        mkdir -p /var/run/polemarch
        chown polemarch:polemarch /projects /var/run/polemarch
        sudo -u polemarch /opt/polemarch/bin/polemarchctl migrate
        sudo -u polemarch /opt/polemarch/bin/uwsgi /opt/polemarch/lib/python2.7/site-packages/polemarch/web.ini
        cat /etc/polemarch/settings.ini
        /bin/bash || exit 0
      "
    external_links:
      - db-server
      - cache-server:memcache-server
      - locks-server:memcache-server
      - rabbitmq-server
    volumes:
      - "project_data:/projects"
    ports:
      - "8080:8080"

volumes:
  project_data:
  db_data: