version: '3'
services:
  db-server:
    image: mysql:latest
    environment:
    - MYSQL_DATABASE=polemarch
    - MYSQL_ROOT_PASSWORD=polemarch
    - MYSQL_USER=polemarch
    - MYSQL_PASSWORD=polemarch
    - MYSQL_HOST=%
    volumes:
      - "db_data:/var/lib/mysql"
  redis-server:
    image: redis:latest
    volumes:
      - "redis_data:/data"
  polemarch:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    command: |
      /bin/bash -c "
        set -e
        curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh | tee ./wait-for-it.sh
        chmod +x wait-for-it.sh
        ./wait-for-it.sh db-server:3306 -s -t 30
        ./wait-for-it.sh redis-server:6379 -s -t 30
        mkdir -p /var/run/polemarch
        /opt/polemarch/bin/polemarchctl migrate
        /opt/polemarch/bin/uwsgi /opt/polemarch/lib/python2.7/site-packages/polemarch/web.ini
        cat /etc/polemarch/settings.ini
        /bin/bash || exit 0
      "
    external_links:
      - db-server
      - redis-server
    volumes:
      - "project_data:/projects"
    ports:
      - "8080:8080"

volumes:
  project_data:
  db_data:
  redis_data: