version: '3'

services:

  polemarch:
    image: polemarch
    build: .
    restart: unless-stopped
    depends_on:
      - redis
      - database
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health/" ]
      interval: 3s
      timeout: 3s
      retries: 3
    tty: true
    volumes:
      - ./settings.ini:/etc/polemarch/settings.ini:ro
    ports:
      - "8080:8080"

  redis:
    image: "redis:6"
    restart: unless-stopped

  database:
    image: mariadb:10.5
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_USER: project_user
      MYSQL_PASSWORD: project_pas
      MYSQL_DATABASE: project_db
      MYSQL_ROOT_PASSWORD: project_root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${POLEMARCH_SQL_ROOT_PASSWORD:-project_root}" ]
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - data-volume:/var/lib/mysql

volumes:
  data-volume:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.100.100.0/24"
