version: '3.3'
services:
  db-server:
    container_name: dbtest
    image: mysql:latest
    environment:
    - MYSQL_DATABASE=polemarch
    - MYSQL_ROOT_PASSWORD=polemarch
    - MYSQL_USER=polemarch
    - MYSQL_PASSWORD=polemarch
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
  memcache-server:
    container_name: cachetest
    image: memcached
  polemarch_test_rpm:
    build:
      context: .
      dockerfile: docker/Dockerfile.test.rpm
    entrypoint: /bin/bash -c "/bin/bash -c \"$${@}\""
    command: |
      /bin/bash -c "
        set -e
        curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > wait-for-it.sh
        chmod +x wait-for-it.sh
        ./wait-for-it.sh db-server:3306
        cd /home/polemarch
        sudo -u polemarch -H /opt/polemarch/bin/coverage run --source='/opt/polemarch/lib/python2.7/site-packages/polemarch' -m polemarch test -v 2 polemarch.main.tests
        sudo -u polemarch -H /opt/polemarch/bin/coverage report -m
        /bin/bash || exit 0
      "
    external_links:
      - db-server
      - cache-server:memcache-server
      - locks-server:memcache-server
