apiVersion: v2
name: polemarch-deployment
version: 0.1.0
dependencies:
- name: centrifugo
  repository: https://centrifugal.github.io/helm-charts
  version: 7.4.0
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.1.3
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.3.6
- name: YAUHC
  alias: polemarch
  repository: https://gitlab.com/api/v4/projects/40345586/packages/helm/stable
  version: 0.1.9
  export-values:
    - parent: werf.image.main
      child: deployments.polemarch.image
